### PR TITLE
JAMES-2520 CI should use newer deployment tests

### PR DESCRIPTION
**Pull request by chibenwa**
Java written logic <3

SMTP, IMAP, webadmin & JMAP are tested

### CODE REVIEW

**Comment by chibenwa** [comment]
Uses work written here: https://github.com/linagora/james-project/pull/1646

**Review by mbaechler — APPROVED** [review]
awesome

**Review by aduprat — APPROVED** [review]

**Comment by mbaechler** [comment]
why it's closed ?

**Comment by chibenwa** [comment]
Because there's conflicts and I don't intend to merge it. I was in a cleaning sprew.

But it fits in a bigger picture: we finally have the opportunity to deprecate and remove the entire linagora/james-jenkins project and I intend to take it.

**Pull request closed without merging**
