### PR TITLE
Issue-24 Publish to Docker Hub

### PR DESCRIPTION
**Pull request by aduprat**

### CODE REVIEW

**Comment by rouazana** [comment]
:+1:

**Comment by mbaechler** [comment]
I would rather generate the dockercfg file from env variables. WDYT ?

**Comment by aduprat** [comment]
To generate the dockercfg file, we need to give three parameters to the docker run command (username, email & password).
That's may be too much...

**Comment by mbaechler** [comment]
The real problem is that you can no longer share the image as you put your secret in it.

**Comment by aduprat** [comment]
Why?
The secret is only in the docker running Jenkins, it's not used in the produced James image.
The login command is only here to push the image to Docker Hub.

**Comment by mbaechler** [comment]
Of course, I meant you can no longer share the jenkins image.

**Comment by aduprat** [comment]
Do we really want to share that image?
We have never discuss on that subject.

**Comment by mbaechler** [comment]
It's not really important, but I find it weird to build private images for the sake of not putting 3 arguments on the command line

**Pull request merged**
