### PR TITLE
Use a tmpfs folder to speed compilation up

### PR DESCRIPTION
**Pull request by chibenwa**
I finally managed to find how to cleanly mount a tmpfs inside a docker container.
So I guess we have here an easy speedup for our tests.

Note : It is not as fast as having the whole docker container in tmpfs, but it is still fine !

### CODE REVIEW

**Comment by mbaechler** [comment]
That's really cool !
:+1:

**Comment by rouazana** [comment]
Do you have an idea why it is needed?
What is so IO consumming: logs? test databases? compilation?

**Comment by mbaechler** [comment]
Could you trace filesystem use with something like this : http://archive09.linux.com/feature/124903 to see what filesystem accesses are and if every write is done in /james-project ?

**Comment by chibenwa** [comment]
Cassandra database mainly
It also helps for HBase
1~2 minute gained on compilation (writing to taget)

It comes with the fact that folder content is lost on reboot, but I think we don't care....

**Comment by chibenwa** [comment]
Sure

**Comment by mbaechler** [comment]
You can already merge this PR, it's already a win. Further enhancement could be in new PRs.

**Comment by rouazana** [comment]
ok :+1:  we should contribute a memory mode to cassandra :)

**Comment by aduprat** [comment]
:+1:

**Comment by chibenwa** [comment]
I do not have the right to merge this... :-(

Once done, re-launching the DSL job import will do the work, I guess....

**Comment by aduprat** [comment]
No, workflow-job is created when starting Jenkins.

**Pull request merged**
